apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-service-config
  namespace: billing-service
data:
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  RABBITMQ_HOST: "rabbitmq-service.rabbitmq.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  RABBITMQ_VHOST: "/"
