apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: billing-service
  labels:
    app: billing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
        - name: billing-service
          image: DOCKERHUB_USERNAME/billing-service:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: billing-service-config
            - secretRef:
                name: billing-service-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
