apiVersion: v1
kind: Secret
metadata:
  name: billing-service-secret
  namespace: billing-service
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-billing:5432/billing_service"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "CHANGE_ME"
  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"
  MERCADOPAGO_ACCESS_TOKEN: "CHANGE_ME"
