apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: billing-service
spec:
  selector:
    app: billing-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
